### ISSUE TITLE
Add programs to install

### ISSUE THREAD

**Issue by Druidblack** [nerethos/docker-stash#14]
Add the following programs to the list of installed programs
python-json-logger
thefuzz

They are used in plugins https://github.com/Serechops/Serechops-Stash

**Comment by masterr2001** [comment]
Should be adressed by #17

**Comment by nerethos** [comment]
Please take a look at my PR and let me know if you think there any issues.

You can test the functionality with nerethos/stash-jellyfin-ffmpeg:testing
