### ISSUE TITLE
Add AMD APU for hardware transcoding

### ISSUE THREAD

**Issue by ZobaJakColbert** [nerethos/docker-stash#32]
Is there a way for using AMD APU for hardware transcoding?

**Comment by nerethos** [comment]
> Is there a way for using AMD APU for hardware transcoding?

The container should be compatible with AMD graphics. I'm not sure if Stash supports it though.

**Comment by ZobaJakColbert** [comment]
It's working on unraid. I added to docker container device /dev/dri:/dev/dri. And when opening video and using HLS transcoding GPU is active.
